# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20160819_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoutire',
            name='entry',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Entry'),
        ),
    ]
