# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20160822_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoutire',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Entry'),
        ),
    ]
